improvement

diff --git a/dualSeq/snakefiles/mapping/combined/combined_pe b/dualSeq/snakefiles/mapping/combined/combined_pe
--- a/dualSeq/snakefiles/mapping/combined/combined_pe
+++ b/dualSeq/snakefiles/mapping/combined/combined_pe
@@ -1,7 +1,6 @@
 from os import listdir
 from os.path import isfile, splitext
 import csv, glob
-import shutil
 
 localrules: plot_statistics
 
@@ -59,20 +58,24 @@ rule star_index:
         mem_mb=%%MEM_MB_STAR%%
     shell:
         """
-        host_gtf, host_ext = os.path.splitext({genome.host})
-        virus_gtf, virus_ext = os.path.splitext({params.filelist[1]})
-        if host_ext != virus_ext:
-            sys.exit("ERROR: Annotation file format of host and virus does not match.")
-        else
-            if "{wildcards.virus}" == "None":
-                shell("STAR --runThreadN {threads} --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input.genome_host} --sjdbGTFfile %%HOST_GTF%% --sjdbOverhang %%STAR_SJ_OVERHANG%% --sjdbGTFfeatureExon %%STAR_FEATURE_EXON%% --sjdbGTFtagExonParentGene %%STAR_GENE_TAG%% --sjdbGTFtagExonParentTranscript %%STAR_TRANSCRIPT_TAG%% --outTmpDir {params.tmp} 2>&1 | tee {log}")
-            else
-                with open({params.ann_file}, 'w') as outfile:
-                    for filename in [%%HOST_GTF%%, {params.filelist[1]}]:
-                        with open(filename, 'r') as infile:
-                            shutil.copyfileobj(infile, outfile)
-                shell("STAR --runThreadN {threads} --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input.genome_host} {params.filelist[0]} --sjdbGTFfile {params.ann_file} --sjdbOverhang %%STAR_SJ_OVERHANG%% --sjdbGTFfeatureExon %%STAR_FEATURE_EXON%% --sjdbGTFtagExonParentGene %%STAR_GENE_TAG%% --sjdbGTFtagExonParentTranscript %%STAR_TRANSCRIPT_TAG%% --outTmpDir {params.tmp} 2>&1 | tee {log}")
-        """
+	host_gtf=%%HOST_GTF%%
+        host_ext="${{host_gtf##*.}}"
+	virus_gtf={params.filelist[1]}
+        virus_ext="${{virus_gtf##*.}}"
+	echo $host_ext
+	echo $virus_ext
+        if [[ "$host_ext" != "$virus_ext" ]]; then
+            echo "ERROR: Annotation file format of host and virus does not match." >&2
+            exit 1
+        elif [[ "{wildcards.virus}" == "None" ]]; then
+		   STAR --runThreadN {threads} --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input.genome_host} --sjdbGTFfile %%HOST_GTF%% --sjdbOverhang %%STAR_SJ_OVERHANG%% --sjdbGTFfeatureExon %%STAR_FEATURE_EXON%% --sjdbGTFtagExonParentGene %%STAR_GENE_TAG%% --sjdbGTFtagExonParentTranscript %%STAR_TRANSCRIPT_TAG%% --outTmpDir {params.tmp} 2>&1 | tee {log}
+	    else
+		   touch {params.ann_file}    
+		   cat %%HOST_GTF%% > {params.ann_file}
+		   cat {params.filelist[1]} >> {params.ann_file}
+		   STAR --runThreadN {threads} --runMode genomeGenerate --genomeDir {output} --genomeFastaFiles {input.genome_host} {params.filelist[0]} --sjdbGTFfile {params.ann_file} --sjdbOverhang %%STAR_SJ_OVERHANG%% --sjdbGTFfeatureExon %%STAR_FEATURE_EXON%% --sjdbGTFtagExonParentGene %%STAR_GENE_TAG%% --sjdbGTFtagExonParentTranscript %%STAR_TRANSCRIPT_TAG%% --outTmpDir {params.tmp} 2>&1 | tee {log}
+	    fi
+	    """
 
 def get_genome(wildcards):
     """Get name of STAR index for sample."""
@@ -217,7 +220,7 @@ rule mapped_both:
     #resources: cpus=1, mem_mb=4000
     shell:
         """
-        samtools view {input.virus} | cut -f1 | awk '{a[$1]=1} END{for(i in a) print i}' > {output.names}
+        samtools view {input.virus} | cut -f1 | awk '{{a[$1]=1}} END{{for(i in a) print i}}' > {output.names}
         samtools view -N {output.names} {input.host} | cut -f1 | sort -u > {output.both} || true
         """
 
